# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      # General file checking
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: end-of-file-fixer
      # JSON files
      - id: check-json
        exclude: .vscode/launch.json
      # YAML files
      - id: check-yaml

  # Checking LUA
  - repo: https://github.com/Calinou/pre-commit-luacheck
    rev: v1.0.0
    hooks:
      - id: luacheck
